// packages/client/src/components/SideNav/SideNav.tsx
import { FC } from 'react';
import { Card, CardContent, CardTitle } from '../ui/card';
import { Link } from 'react-router-dom';

export const SideNav: FC = () => {
  return (
    <nav className="pt-24 w-72 h-screen fixed space-y-4 mt-4 px-4">
      <Card>
        <CardTitle>main menu</CardTitle>
        <CardContent>
          <ul>
            <li>
              <Link to="/">home</Link>
            </li>
            <li>
              <Link to="/referendums">referendums</Link>
            </li>
          </ul>
        </CardContent>
      </Card>
    </nav>
  );
};

// packages/ui/components/Sidenav/Sidenav.svelte
<script lang="ts">
  import SidenavItem from './SidenavItem.svelte';
</script>

<nav class="pt-24 w-72 h-screen fixed space-y-4 mt-4 px-4">
  <div class="card w-full bg-base-100 shadow px-8 py-4">
    <ul class="space-y-4">
      <SidenavItem href="/" icon="home">home</SidenavItem>
      <SidenavItem href="/referendums" icon="activity">referendums</SidenavItem>
    </ul>
  </div>
</nav>
